language: python

python:
  - "2.7"

notifications:
      slack: stockportfolio:cnyIsQVuBjUgajhm9YN9OaI4

install: "pip install -r requirements.txt"
script: python -m unittest discover -s . -p '*_test.py'
